#
# This file was created by Xilinx Vitis tool.
#


#
# tools
#

RM = rm -f
RMDIR = rm -rf



#
# variables
#

SDCARD_GEN = sdcard_gen
GENERATE_BIF = ::scw::generate_bif

XPFM_PATH = D:/Github/Zybo-Z7/sw/ws/system_wrapper/export/system_wrapper/system_wrapper.xpfm
SYS_CONFIG = system_wrapper
DOMAINS = domain_ps7_cortexa9_0
BIF_PATH = C:/Users/Jason/workspace/Zybo-Z7-10-DMA_system/Debug/system.bif

BITSTREAM_PATH = C:/Users/Jason/workspace/Zybo-Z7-10-DMA/_ide/bitstream/system_wrapper.bit
SD_FILES = --elf C:/Users/Jason/workspace/Zybo-Z7-10-DMA/Debug/Zybo-Z7-10-DMA.elf,ps7_cortexa9_0

#
# primary build targets
#

all: package

package:
	-@echo Generating bif file for the system project
	generate_system_bif.bat 55338 ${XPFM_PATH} ${DOMAINS} ${BIF_PATH}
	${SDCARD_GEN} --xpfm ${XPFM_PATH} --sys_config ${SYS_CONFIG} --bif ${BIF_PATH} --bitstream ${BITSTREAM_PATH} ${SD_FILES}

clean:
	$(RMDIR) ./_sds
	${RMDIR} package
	${RM} system.bif

.PHONY: all package clean


